#!/bin/bash

#####################
# sc-rna-10x driver #
#####################

### This script will 
### * Run the sc-rna-10x pipeline on data in current runfolder
### * Modify standard nextflow.config to project specific 
### * Generate project folder in shared/ctg-delivery/sc-rna-10x
###  -> Here it will store nextflow.config, nf-pipeline, samplesheet in ctg-log 
###  -> Write pipeline output 
### * nf-Pipeline writes qc to shared/ctg-qc/sc-rna-10x

echo "first echo"
# Initialize variables
runfolder=$(pwd)
run=$(basename $runfolder)
demux="ON"
resume='n'
index='dual'
version='deployed'

# usage message 
usage() {

    echo ""
    echo "Usage: sc-rna-10x [ -v CTG-PIPELINE-VERSION ] [ -i META_ID ] [ -s SAMPLESHEET ] [ -a INDEX-TYPE ] [ -b BCL2FASTQ-ARG ] [ -r RESUME ] [ -c CUSTOM-GENOME ] [ -d DEMUX-OFF ] [ -h HELP ] "  1>&2
    echo ""
    echo ""
    echo "Optional arguments: "
    echo "VERSION       -v : Set specific version to run of the nextflow pipeline. Default will run current deployed version (in /shared/ctg-pipelines/ctg-sc-rna-10x/. If set to '-r 2' it will run v2, which is in -pipelines/ctg-sc-rna-10x/v2. If -v X it will choose -pipelines/ctg-sc-rna-10x/vX"
    echo "META-ID       -i : Set 'meta-id' for runfolder (e.g. 210330-10x). Default: Takes date of runfolder + run ID in runfolder name and adds sc-rna-10x as suffix. E.g. '210330_A00681_0334_AHWFKTDMXX' becomes 210330_0334-sc-rna-10x "
    echo "SAMPLESHEET   -s : Set samplesheet used for run (Default: CTG_SampleSheet.sc-rna-10x.csv) "
    echo "INDEX-TYPE    -a : Set -a if single index uses. (Default: dual) "  
    echo "BCL2FASTQ-ARG -b : String with bcl2fastq argument. e.g. '--minimum-trimmed-read-length 20 --mask-short-adapter-reads 20' "
    echo "RESUME        -r : Set if to resume nf-pipeline"
    echo "CUSTOM-GENOME -c : Path to custom reference genome if needed. Skip if human/mouse defined in samplesheet "
    echo "DEMUX-OFF     -d : Set flag to skip mkfastq (then fastq must be in FQDIR) "
    echo "HELP          -h : print help message" 
   
}

exit_abnormal() {
    usage
    exit 1
}

# Read and control input arguments 
while getopts i:s:v:b:ac:rdh opt; do
    case $opt in
	v) version=$OPTARG
	    ;;
	i) id=$OPTARG
	    ;;
	s) sheet=$OPTARG
	    ;;
	a) index="single"
	    ;;
	b) b2farg=$OPTARG
	    ;;
	r) resume="y"
	    ;;
	c) custom_genome=$OPTARG
	    ;;
	d) demux="OFF"
	    ;;
	h) exit_abnormal
	    ;;
	\?) echo "> Error: Invalid option -$OPTARG" >&2
	    exit_abnormal ;;
	:) echo "> Error: -${OPTARG} requires an argument: -i needs project-id and -s need samplesheet name! "
	    exit_abnormal ;;
    esac
done

## Check arguments
shift "$(( OPTIND -1 ))"

# Check samplesheet name
if [ -z $sheet ]; then
    echo ""; echo "> WARNING! No samplesheet specified"
    sheet="CTG_SampleSheet.sc-rna-10x.csv"
    echo "- Using 'CTG_SampleSheet.sc-rna-10x.csv'"
    if [ ! -f $sheet ]; then
	echo "> Error: CTG_SampleSheet.csv does not exist (in current dir)"
	echo "- Please specify correct samplesheet, or create a CTG_SampleSheet.sc-rna-10x.csv in current runfolder"
	exit_abnormal
    fi
fi

# Check meta-id - assign project number if not specified
if [ -z $id ]; then
    echo "> No meta-ID specified"
    metaid=$(grep "ProjectID" $sheet | cut -f2 -d"," | tr -d '\n\r')
    if [ -z $metaid ]; then
	metaid=$(echo $run | cut -f1,3 -d"_")
	id="${metaid}-sc-rna-10x"
    else
	id="${metaid}"
    fi
    echo "- Using: '${id}'"
fi

projdir="/projects/fs1/shared/ctg-projects/sc-rna-10x/$id/"

# Check if meta-ID already exist
if [ "$resume" == 'n' ] && [ -d $projdir ]; then
    # Prompt user to approve overwriting current sc-rna-10x project-folder
    read -p "> WARNING: $id has been used before:

The following directories already exist:
- $projdir
- /projects/fs1/shared/ctg-qc/sc-rna-10x/$id 
- /projects/fs1/nas-sync/ctg-delivery/sc-rna-10x/$id 


Do you want to overwrite these folders? 

(y/n)  ... : " prompt
    if [[ $prompt != "y" ]]
    then 
	echo "> Exiting: Please provide new [ -i metaID ] !"
	exit_abnormal
    else
	echo "> Deleting content of the folders.. "
	rm -r $projdir/*
	rm -r /projects/fs1/shared/ctg-qc/sc-rna-10x/$id/*
	rm -r /projects/fs1/nas-sync/ctg-delivery/sc-rna-10x/$id/*
    fi
else
    echo "> Proceeding with project '$id' "
fi

################
# Set up files #
################

# Creating project dir for logging pipeline
mkdir -p $projdir

# Copy nextflow script and config to project folder
if [ $version == "deployed" ]; then
    piperoot="/projects/fs1/shared/ctg-pipelines/ctg-sc-rna-10x/"
else
    piperoot="/projects/fs1/shared/ctg-pipelines/ctg-sc-rna-10x/v${version}"
fi

nf_pipe="${piperoot}/pipe-sc-rna-10x.nf"
nf_config="${piperoot}/nextflow.config"
nf_bin="${piperoot}/bin/"

cp $nf_pipe $projdir
cp $nf_config $projdir
cp -r $nf_bin $projdir

# Edit config file
proj_conf=$projdir/nextflow.config
sed "s/xmetaidx/$id/g" $proj_conf > tmp.txt; mv tmp.txt $proj_conf
sed "s|xrunfolderx|$runfolder|g" $proj_conf > tmp.txt; mv tmp.txt $proj_conf
sed "s/xsamplesheetx/$sheet/g" $proj_conf > tmp.txt; mv tmp.txt $proj_conf
sed "s/xbcl2fastqargx/$b2farg/g" $proj_conf > tmp.txt; mv tmp.txt $proj_conf
sed "s/xindextypex/$index/g" $proj_conf > tmp.txt; mv tmp.txt $proj_conf
if [ ! -z $custom_genome ]; then
    sed "s/xcustomgenomex/$custom_genome/g" $proj_conf > tmp.txt; mv tmp.txt $proj_conf
fi
if [ $demux == "ON" ];then
    sed "s/xdemuxx/y/g" $proj_conf > tmp.txt; mv tmp.txt $proj_conf
else
    sed "s/xdemuxx/n/g" $proj_conf > tmp.txt; mv tmp.txt $proj_conf
fi

# Copy edited config to runfolder
cp $proj_conf $runfolder/$id.nextflow.config
# Copy samplesheet to project folder (ctg-projects..)
cp $sheet $projdir


##############
# Print info #
##############
echo ""
echo "> The following arguments are chosen:"
echo "sc-rna-10x version : $version"  
echo "Pipeline           : $nf_pipe"
echo "ID                 : $id"
echo "Runfolder          : $runfolder " 
echo "Sheet              : $sheet"
echo "Index-type         : ${index}-index"
echo "Bcl2fastq arg      : '$b2farg'"
if [ -z $custom_genome ]; then
    echo "Custom Genome      : NONE "
else
    echo "Custom Genome      : $custom_genome "
fi
if [ $demux == "ON" ]; then
    echo "Demux              : YES "
else
    echo "Demux              : NO "
fi
if [ $resume == "y" ]; then
    echo "Resume             : YES "
else
    echo "Resume             : NO "
fi

echo ""
echo "Runfolder          : $runfolder "
echo "Project Logfolder  : /projects/fs1/shared/ctg-projects/sc-rna-10x/$id"
echo "QC Logfolder       : /projects/fs1/shared/ctg-qc/sc-rna-10x/$id"
echo "Output             : /projects/fs1/nas-sync/ctg-delivery/sc-rna-10x/$id"
echo ""

# Prompt user to approve running in current directory and input
read -p "> WARNING: Can only be run from within runfolder! 

- Are you in runfolder in which you want run? 
- And is input described above correct ?  

(y/n)  ... : " prompt
if [[ $prompt != "y" ]]
then 
    echo "> Exiting: Go to runfolder!"
    exit 0
fi

#####################
# Start nf-pipeline #
#####################

# Go to ctg-project folder to execute pipeline
cd $projdir

if [ $resume == "y" ]; then
    nohup nextflow run $nf_pipe -resume > log.nf.sc-rna-10x.$id &
else
    nohup nextflow run $nf_pipe > log.nf.sc-rna-10x.$id &
fi
echo ; echo 
echo "#################################"
echo "# sc-rna-10x pipeline submitted #"
echo "#################################"
echo ; echo 





